Nomi/gloss 20210302 02
crate/crate pull request #11144
Opened 2021-03-17 11:27 UTC by norosa

added "function" to the glossary. we have a bunch of documentation for specific types of function. the bulk of the cross-references added link to these specific function docs

the commit message has more details

where I added cross-references, I ended up reformatting the RST for line-length reasons. I took the opportunity to add a lot of related RST improvements

this is a BIG changeset because there were so many function-related terms to cross-reference and so many RST problems. I think could have improved things if I made one commit per specific function type

if you would like, I think I could probably decompose the changes into three commits:

- one for changes to the glossary
- one for changes to the main docs
- one for changes to the release notes

2021-03-18 17:30 UTC, norosa commented
@mkleen can I get your review on this? apologies for the size of the diff. I am going to try to spread reviews around the team a bit as I continue work on the glossary

2021-03-19 10:30 UTC, mkleen commented
It would be really nice if you could split that up a little bit.

2021-03-19 10:32 UTC, mkleen commented
If you can separate formatting changes from content changes that would be also helpful, because I am mainly looking for the content.

2021-03-19 16:16 UTC, amotl requested changes
Wow, that is truly an impressive amount of improvements all over the place. Thank you very much.

I tried to review this whole patch as thoroughly as possible and added some comments along the lines. Some of them (specifically about amendments to punctuations) might not be valid and may get skipped unresolved.

2021-03-19 16:16 UTC, amotl commented on docs/sql/statements/drop-function.rst
>  specified.
```suggestion
<user-defined-functions>`. The function name and the respective argument types
must be specified.
```

2021-03-19 16:16 UTC, amotl commented on docs/sql/statements/select.rst
> +``SELECT`` this name is just used to label the column for display. To specify
```suggestion
``SELECT``, this name is just used to label the column for display. To specify
```

2021-03-19 16:16 UTC, amotl commented on docs/sql/statements/select.rst
> +column reference then the chosen name is the same as that column's name. In
```suggestion
column reference, then the chosen name is the same as that column's name. In
```

2021-03-19 16:16 UTC, amotl commented on docs/sql/statements/select.rst
> +more complex cases a :ref:`function <gloss-function>` or type name may be used,
```suggestion
more complex cases, a :ref:`function <gloss-function>` or type name may be used,
```

2021-03-19 16:16 UTC, amotl commented on docs/sql/statements/select.rst
> +rows that share the same values for the grouped expressions.
```suggestion
The optional ``GROUP BY`` clause will condense all selected rows that
share the same values for the grouped expressions into a single row.
```

2021-03-19 16:16 UTC, amotl commented on docs/sql/statements/select.rst
> +within a resulting row of a group by clause.
```suggestion
within a resulting row of a ``GROUP BY`` clause.
```

2021-03-19 16:16 UTC, amotl commented on docs/sql/statements/select.rst
> +  A having condition is any expression that evaluates to a result of type
```suggestion
  A ``HAVING`` condition is any expression that evaluates to a result of type
```

2021-03-19 16:16 UTC, amotl commented on docs/sql/statements/select.rst
> +more complex ordering ``UNION ALL`` must become a subselect and the more
```suggestion
more complex ordering, ``UNION ALL`` must become a subselect and the more
```

2021-03-19 16:16 UTC, amotl commented on docs/sql/statements/select.rst
> +Ordering of the outcome is not guaranteed unless ``ORDER BY`` is used.
```suggestion
The ordering of the outcome is not guaranteed unless ``ORDER BY`` is used.
```

2021-03-19 16:16 UTC, amotl commented on docs/sql/statements/select.rst
> +expression allows to define the direction in which values have are sorted. The
```suggestion
expression allows to define the direction in which values are sorted. The
```

2021-03-19 16:16 UTC, amotl commented on docs/sql/statements/select.rst
> +for ``ASC`` is ``NULLS LAST`` and the default for ``DESC`` is ``NULLS FIRST``.
```suggestion
If ``NULLS FIRST`` is specified, null values sort before non-null values. If
``NULLS LAST`` is specified, null values sort after non-null values.  If neither
is specified, nulls are considered larger than any value. That means the default
for ``ASC`` is ``NULLS LAST`` and the default for ``DESC`` is ``NULLS FIRST``.
```

2021-03-19 16:16 UTC, amotl commented on docs/sql/statements/select.rst
> +The optional ``LIMIT`` clause allows to limit the number or retured result
```suggestion
The optional ``LIMIT`` clause allows to limit the number of returned result
```

2021-03-22 10:03 UTC, norosa commented on docs/general/ddl/data-types.rst
> +TIME ZONE zone.
asked in Slack

2021-03-22 10:08 UTC, norosa commented on docs/general/dql/geo.rst
>  ``geohash`` you can query that column using the ``MATCH`` predicate with
replaced your "-" with a comma as I don't like the idea of combining a literal with normal prose like that. but otherwise great suggestion

2021-03-22 10:12 UTC, norosa commented on docs/general/user-defined-functions.rst
> +Currently, CrateDB only supports JavaScript user-defined functions.
slightly reworded to keep the emphasis on "JavaScript", but thanks!

2021-03-22 10:16 UTC, norosa commented on docs/sql/general/constraints.rst
> +``CHECK`` constaints can be removed :ref:`drop-constraint`.
moved this up to the second para where `DROP CONSTRAINT` is already mentioned

2021-03-22 10:29 UTC, mkleen commented on docs/general/ddl/data-types.rst
> +TIME ZONE zone.
AFAIK we only support `AT TIME ZONE` not the `AT TIME ZONE INTERVAL` variant.

2021-03-22 11:35 UTC, norosa commented
@amotl thanks SO much for your comprehensive review

I have pushed fixups

if everything looks good to you, can I get an ack?

2021-03-22 12:26 UTC, amotl requested changes
Hi again,

thank you for incorporating the many suggested changes. I've spotted a few more places (more or less just typos) and added corresponding comments.

With kind regards,
Andreas.

2021-03-22 12:26 UTC, amotl commented on docs/general/ddl/sharding.rst
> +    :ref:`CREATER TABLE: CLUSTERED <sql-create-table-clustered>`
```suggestion
    :ref:`CREATE TABLE: CLUSTERED <sql-create-table-clustered>`
```

2021-03-22 12:26 UTC, amotl commented on docs/general/user-defined-functions.rst
> +Function arguments and return values can be any of any supported :ref:`data
```suggestion
Function arguments and return values can be of any supported :ref:`data
```

2021-03-22 12:26 UTC, amotl commented on docs/sql/general/lexical-structure.rst
> +The table bellow lists all *reserved key words* in CrateDB. These need to be
```suggestion
The table below lists all *reserved key words* in CrateDB. These need to be
```

2021-03-22 12:26 UTC, amotl commented on docs/sql/statements/create-table.rst
> +  Rejecting any column on insert, update or copy from which is not defined in
```suggestion
  Rejecting any column on ``INSERT``, ``UPDATE``, or ``COPY FROM``, which is not defined in
```

2021-03-22 12:26 UTC, amotl commented on docs/sql/statements/create-table.rst
> +  New columns can be added using insert, update or copy from. New columns added
```suggestion
  New columns can be added using ``INSERT``, ``UPDATE``, or ``COPY FROM``. New columns added
```

2021-03-22 12:26 UTC, amotl commented on docs/sql/statements/create-table.rst
> +  retrieve them, sort by them and use them in where clauses.
```suggestion
  retrieve them, sort by them and use them in ``WHERE`` clauses.
```

2021-03-22 12:26 UTC, amotl commented on docs/sql/statements/select.rst
> +The optional ``LIMIT`` clause allows to limit the number of retured result
```suggestion
The optional ``LIMIT`` clause allows to limit the number of returned result
```

2021-03-22 13:40 UTC, norosa commented
@amotl omg thanks! pushed a fixup

2021-03-22 13:47 UTC, amotl commented
Linkchecker is croaking:
https://github.com/crate/crate/pull/11144/checks?check_run_id=2166475385

Nevertheless, I will acknowledge this patch. Thank you very much again!

2021-03-22 13:47 UTC, amotl approved these changes

2021-03-22 17:52 UTC, merged