Improve SQL docs for creating and dropping repositories
crate/crate pull request #11439
Opened 2021-06-02 17:40 UTC by norosa

Spotted an opportunity to tidy up the SQL syntax docs for `CREATE REPOSITORY` and went for it.

Specifically:

- For `create-repository.rst`:

  - Improve intro and add cross-references

  - Add missing ref labels and tidy up nomenclature of ref labels throughout the whole doc

  - General copyedits for clarity, style, grammar, and so on

  - Tidied up and improved section/headings hierarchy and use of TOCs

  - Converted all params to use definition-style markup

        **Example**
          This is an example of the style used.

  - Improved use of admonitions and expanded/reworked explanations where necessary to improve clarity

  - Minor edits for the statement synopsis to improve readability (i.e., `repository_parameter` renamed `parameter_name`)

  - Standardized wording of duplicate parameter definitions

  - Standardized ordering of parameters

  - Added external links where helpful (e.g., to specific Hadoop, AWS, and Azure resources)

  - Corrected `readonly` parameter to `url` for `url` type repositories

- For `drop-repository.rst`:

  - Changes to match the above

- For other files:

  - Update ref labels to match changes above

2021-06-02 17:42 UTC, norosa commented
@mkleen while rewording for clarity, I may have introduced errors. my recordings reflect my best understanding of what is being documented. in a few instances, I double-checked with the Elasticsearch docs or by looking at the source code directly. but there is a chance I have missed something subtle so I welcome close scrutiny

2021-06-03 07:50 UTC, mkleen commented on docs/sql/statements/create-repository.rst
> +    IAM role will provide the necessary credentials when required.
I think it is important to mention that when Amazon I AM Roles are used for authentication, that these roles must be provided by the underlying container where CrateDB is deployed.

2021-06-03 07:55 UTC, mkleen requested changes
Very good work, i left one point to follow up.

2021-06-04 09:16 UTC, norosa commented
@mkleen thanks for the review! pushed a fixup. can you check? thx!

2021-06-04 09:18 UTC, norosa commented on docs/sql/statements/create-repository.rst
> +    the necessary credentials when required.
@mkleen changed this

2021-06-04 10:25 UTC, mkleen commented on docs/sql/statements/create-repository.rst
> +    the necessary credentials when required.
Perfect, thank you!

2021-06-04 10:26 UTC, mkleen approved these changes
👍

2021-06-04 12:11 UTC, merged