Improve `README`, update `.gitignore`
crate/crate pull request #11559
Opened 2021-07-13 17:51 UTC by norosa

- For `README`:

  - Expand and improve intro description and list of features.

  - Add links to key phrases to improve cross-referencing to important resources and documentation.

  - Minor formatting improvements and copyediting.

- Added `_venv` to `.gitignore` for compatibility with older (manual) ways of building the docs.

2021-07-13 17:53 UTC, norosa commented
this work was the initial work that ended up with me diving into the main docs so that I could add the necessary RST labels for the links I wanted to add

I have created this as a draft PR for now, because the links will not work until the rest of the changes on https://github.com/crate/crate/pull/11558/commits/801089b23412e75313d9955ac9278e0643463e4e have been merged to master (and are released)

the (and released) part is important, because changes to the CrateDB docs do now show up for the `latest` version (used in the links) until they are included in a stable release

2021-07-28 13:24 UTC, amotl requested changes
Hi Naomi,

I appreciate the improvements and would like to get them merged. Can we try to make it happen after #11558 has been merged?

I also spotted two minor typos.

With kind regards,
Andreas.

2021-07-28 13:24 UTC, amotl commented on README.rst
> +- Use standard `SQL`_ via the `PostgreSQL wire protocol` or an `HTTP API`.
```suggestion
- Use standard `SQL`_ via the `PostgreSQL wire protocol`_ or an `HTTP API`_.
```

2021-08-30 14:44 UTC, amotl commented on README.rst
> +- Geospatial data types and search capability, time-series support, and realtime fulltext
Thank you, I've updated the patch according to your suggestions.

2021-08-30 15:27 UTC, merged