WIP
crate/crate pull request #11570
Opened 2021-07-15 16:49 UTC by norosa

WIP

2021-07-28 13:33 UTC, amotl requested changes
Thanks again for all those improvements. I added some comments about minor hiccups.

2021-07-28 13:33 UTC, amotl commented on docs/general/builtins/scalar-functions.rst
> +example, if the string contains non-identifier characters, keywords or would be
```suggestion
example, if the string contains non-identifier characters, keywords, or would be
```

2021-07-28 13:33 UTC, amotl commented on docs/general/builtins/scalar-functions.rst
> +    In both cases, the scalar functions lpad and rpad, do now accept a len
```suggestion
    In both cases, the scalar functions `lpad` and `rpad`, do now accept a `len`
```

2021-07-28 13:33 UTC, amotl commented on docs/general/builtins/scalar-functions.rst
> +    For example if ``select distance(...)`` returns 0.0 an equality check with
```suggestion
    For example, if ``select distance(...)`` returns 0.0, an equality check with
```

2021-08-03 12:39 UTC, amotl approved these changes
I believe this patch will be good to go but I would also like to see someone else have a look.

2021-08-03 12:54 UTC, mkleen approved these changes

2021-08-03 12:56 UTC, merged

2021-08-04 12:24 UTC, norosa commented
thanks so much!