Do not use FieldExistsQuery over REF that is arg of NON_NULLABLE function
crate/crate pull request #15280
Opened 2024-01-03 22:43 UTC by jeeminso

## Summary of the changes / Why this improves CrateDB

## Checklist

 - [ ] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [ ] Touched code is covered by tests
 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [ ] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

2024-01-03 23:11 UTC, jeeminso commented on server/src/main/java/io/crate/expression/predicate/NotPredicate.java
> +                context.accumulate(childContext);
accumulating the context is only there to keep the original behaviour of the top-level NullabilityContext.

2024-01-03 23:13 UTC, jeeminso commented on server/src/main/java/io/crate/expression/predicate/NotPredicate.java
> +                arg.accept(this, childContext);
This allows the leaf Reference to see if there is any function that are `NON_NULLABLE` in the path from the top-level  node down the itself.

2024-01-08 15:33 UTC, jeeminso commented
Hi @mkleen could you also have a quick look at this draft? Thank you

2024-01-10 01:48 UTC, jeeminso commented
> the undocumented bug is not a regression from `master`, fails on `5.5.0` as well.

I think this cannot be easily back-ported since this depends on https://github.com/crate/crate/commit/4428eb1555069f2325277ee99bd271af651b8425.

2024-01-10 12:18 UTC, mkleen requested changes

2024-01-10 13:00 UTC, mkleen commented on server/src/main/java/io/crate/expression/predicate/NotPredicate.java
> +                arg.accept(this, NullabilityContext.of(context));
I think you can just pass the same context and it will be the same result.

2024-01-10 14:23 UTC, jeeminso commented on server/src/main/java/io/crate/expression/predicate/NotPredicate.java
> +        private AtomicBoolean enforceThreeValuedLogic = new AtomicBoolean(false);
Unlike `isNullable`, a single instance of `enforceThreeValuedLogic` is purposely shared across all instances of `NullabilityContext`. I will try to attach better comments.

2024-01-10 15:43 UTC, jeeminso commented on server/src/main/java/io/crate/expression/predicate/NotPredicate.java
> +                context.isNullable = isNullable;
Thank you for reviewing @mkleen . I think the static method `of` was the cause of the confusion. Please check again.

2024-01-10 18:09 UTC, mkleen approved these changes
Nice! Thank you!

2024-01-10 19:31 UTC, merged