Explicitly mention BM25 in score docs
crate/crate pull request #15355
Opened 2024-01-16 09:45 UTC by romseygeek

2024-01-16 18:02 UTC, amotl requested changes
Thank you Alan. I've just added some suggestions. Feel free to use them or not.

2024-01-16 18:02 UTC, amotl commented on docs/general/ddl/system-columns.rst
> +  the query filter, and makes most sense for full text queries.
While being at it, I just wanted to add guidance about the "why so?" details. I hope you get the idea, and will be able to come up with something more fluent.
```suggestion
  the query filter, and makes most sense for full text queries, by using it
  as a rank indicator to know how good the expression matches the
  document, compared to others.
```

2024-01-17 09:34 UTC, romseygeek commented on docs/general/ddl/system-columns.rst
> +  The score is calculated using Lucene's BM25 Similarity implementation, which
I tried to find a decent page to link to here, but there is surprisingly little on the public web.  There's the [lucene javadoc](https://lucene.apache.org/core/9_9_0/core/org/apache/lucene/search/similarities/BM25Similarity.html) but that's pretty sparse, and then there's a scattering of blog posts from elastic and open source connections, but they're fairly specific to elasticsearch or Solr.  There's also the [Wikipedia page for Okapi BM25](https://en.wikipedia.org/wiki/Okapi_BM25) which gives a good overview of the algorithm, but our implementation is subtly different.

Maybe I should link to both the lucene javadoc and the Wikipedia page, and say something like "The score is calculated using Lucene's BM25Similarity implementation, based on the widely-used Okapi BM25 algorithm"?

2024-01-17 10:11 UTC, hlcianfagna commented on docs/general/ddl/system-columns.rst
> +  The score is calculated using Lucene's `BM25Similarity implementation`,
```suggestion
  The score is calculated using Lucene's `BM25Similarity implementation`_ ,
```

2024-01-17 10:11 UTC, hlcianfagna commented on docs/general/ddl/system-columns.rst
> +  based on the widely-used `Okapi BM25` algorithm.  This uses a combination
```suggestion
  based on the widely-used `Okapi BM25`_ algorithm.  This uses a combination
```

2024-01-17 10:41 UTC, hlcianfagna approved these changes

2024-01-17 12:17 UTC, amotl approved these changes

2024-01-17 12:17 UTC, amotl commented on docs/general/ddl/system-columns.rst
> +  score to be used for ranking.
Excellent! Thanks.

2024-01-17 12:17 UTC, amotl commented on docs/general/ddl/system-columns.rst
> +  based on the widely-used `Okapi BM25`_ algorithm.  This uses a combination
Perfect. Thanks.

2024-01-17 14:26 UTC, merged

2024-01-18 07:26 UTC, ckurze commented
@romseygeek @amotl I just had a look at https://cratedb.com/docs/crate/reference/en/master/general/ddl/system-columns.html - the links are unfortunately not working. Could you pls. check?

Thanks

2024-01-18 09:00 UTC, romseygeek commented
Weird, I thought we'd fixed those.  I've opened https://github.com/crate/crate/pull/15396