Fall back to GenericFunctionQuery when the pattern literal is not a pattern
crate/crate pull request #16605
Opened 2024-09-11 17:00 UTC by jeeminso

## Summary of the changes / Why this improves CrateDB
Fixes https://github.com/crate/crate/issues/16593. The bug scenario occurs because when an argument of `like any` is a literal, CrateDB assumed it as the pattern literal.(ignoring the possibility that the references could contain patterns) To fix this, we need to fall back to generic function query when the literal does not contain any wildcards.  

## Checklist

 - [x] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

2024-09-17 12:01 UTC, matriv commented on docs/appendices/release-notes/5.8.3.rst
> +
just a heads up, since 5.8.3 is currently being released, it will have to be moved to 5.8.4.rst.

2024-09-17 12:47 UTC, seut requested changes
Please see https://github.com/crate/crate/issues/16593#issuecomment-2355658931. I don't think we should make it work.

2024-09-18 11:16 UTC, mfussenegger commented
I'd tend to handle this as part of https://github.com/crate/crate/issues/16619 instead of bugfix.
We should make sure we've a coherent picture of how these any/all functions behave to avoid churn

2024-09-18 13:15 UTC, closed without merging

2024-09-18 13:15 UTC, jeeminso commented
Thank you @mfussenegger closing.