Change column policies of objects from system tables to IGNORED
crate/crate pull request #17103
Opened 2024-12-04 18:16 UTC by jeeminso

## Summary of the changes / Why this improves CrateDB
experimenting

## Checklist

 - [ ] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [ ] Touched code is covered by tests
 - [ ] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

2024-12-04 19:10 UTC, jeeminso commented
There is a single test failure with 1). It is due to comparison against an object literal which is DYNAMIC by default causing the object from sys table to be cast from IGNORED > DYNAMIC.

2024-12-05 01:19 UTC, jeeminso commented
There is also a single test failure from option 2). But it seems like a testcase problem.

2024-12-05 01:55 UTC, jeeminso commented
Hi @seut, I think there are two ways to solve this, the first and the third commit. Could you take a look at them?

2024-12-05 15:31 UTC, seut reviewed
~Shouldn't we rather make `sys.nodes.attributes` a typed object?~
Ignore this please, it's a user-defined map 🤦

2024-12-09 10:44 UTC, seut reviewed
Looks good.
I spotted the usage of `UNTYPED` also at https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/metadata/sys/SysSegmentsTableInfo.java#L66, could you fix this as well please? Thanks!

2024-12-09 10:48 UTC, mfussenegger requested changes

2024-12-09 10:48 UTC, mfussenegger commented on server/src/main/java/io/crate/metadata/sys/SysNodesTableInfo.java
> +        .add("attributes", ObjectType.of(ColumnPolicy.IGNORED).build(), NodeStatsContext::attributes)
```suggestion
        .addDynamicObject("attributes", STRING, NodeStatsContext::attributes)
```

2024-12-09 10:48 UTC, mfussenegger commented on server/src/testFixtures/java/io/crate/testing/SQLResponseAssert.java
> +    }
```suggestion
```

We should assert the actual expected result if possible

2024-12-09 10:48 UTC, mfussenegger commented on server/src/test/java/io/crate/integrationtests/SysNodesITest.java
> +        assertThat(response).isNotEmpty();
```suggestion
        execute("SELECT attributes['color'] FROM sys.nodes order by 1");
        assertThat(response).hasRows(
            "blue",
            "red"
        );
```

2024-12-09 16:23 UTC, jeeminso commented
Thank you for reviewing @seut @mfussenegger . Please check for the updates.

2024-12-09 16:27 UTC, mfussenegger approved these changes

2024-12-09 16:38 UTC, jeeminso commented
@mergifyio requeue

2024-12-09 16:45 UTC, merged