Throw an expected exception for `EXPLAIN ANALYZE INSERT`
crate/crate pull request #17162
Opened 2024-12-19 20:36 UTC by jeeminso

## Summary of the changes / Why this improves CrateDB
Fixes part of https://github.com/crate/crate/issues/17159. Now the reported scenario behaves as expected:
```
cr> EXPLAIN analyze INSERT INTO t (id) VALUES (2);
UnsupportedFeatureException[EXPLAIN ANALYZE is not supported for Insert{table=Table{only=false, t, partitionProperties=[]}, duplicateKeyContext=DuplicateKeyContext{type=NONE, onDuplicateKeyAssignments=[], constraintColumns=[]}, columns=[id], insertSource=Query{with=Optional.emptyqueryBody=Values{rows=[ValuesList{values=[2]}]}, orderBy=[], limit=Optional.empty, offset=Optional.empty}, returning=[]}]
```

## Checklist

 - [ ] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [ ] Touched code is covered by tests
 - [ ] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

2024-12-19 21:36 UTC, jeeminso commented on server/src/main/java/io/crate/planner/node/management/ExplainPlan.java
> +        }
Similar to https://github.com/crate/crate/blob/c52cedb35132d477bbbb01d019975ecea5180da5/server/src/main/java/io/crate/planner/operators/LogicalPlanner.java#L598-L603

2024-12-19 21:40 UTC, jeeminso commented on server/src/main/java/io/crate/planner/node/management/ExplainPlan.java
> +        }
The first commit is enough for the reported scenario but just for the completeness...

2024-12-20 01:28 UTC, jeeminso commented
The bug also reported that it was unable to kill the hanging job. What happened was that CrateDB expects an execution plan that is ready to be executed to not fail to execute. But the explain plan did fail to execute(it never became an active running task) while the jobs-log service logged that it was executed properly. Kill actions could not kill because there were no running tasks to kill. Jobs-log service never cleaned up the job because it never received an execution completed signal.

I do not see anything to be done for this part. The second commit is supposed to signal the jobs-log service with an exceptional completion signal which will cause the jobs log to be removed.

2024-12-20 07:25 UTC, BaurzhanSakhariev approved these changes
Thanks!

2024-12-20 08:26 UTC, seut requested changes

2024-12-20 08:26 UTC, seut commented on docs/appendices/release-notes/5.9.6.rst
> +  is not yet supported.
Please remove `yet` as this sounds it will be supported soon while it is unclear if we'll ever support it.
```suggestion
  is not supported.
```

2024-12-20 08:26 UTC, seut commented on server/src/main/java/io/crate/analyze/ExplainStatementAnalyzer.java
> +
AFAIK we don't support `EXPLAIN ANALYZE COPY` as well.
```suggestion
```

2024-12-23 14:42 UTC, closed without merging